# Generated by Django 4.2.7 on 2024-01-02 16:21

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("title", models.CharField(max_length=50)),
                (
                    "book_id",
                    models.IntegerField(
                        default=secrets.token_hex,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("pagesCount", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "stud_id",
                    models.IntegerField(
                        max_length=9, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
