# Generated by Django 4.2.7 on 2024-01-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="static/uploadedImages/default.jpeg",
                upload_to="static/uploadedImages/",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="stud_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
