# Generated by Django 4.2.7 on 2024-01-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_book_image_alter_book_book_id_alter_student_stud_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(
                default="Miscellaneous Books Category", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, verbose_name="Enter Email"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Enter Full Name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="stud_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Enter Roll No."
            ),
        ),
        migrations.AlterModelTable(
            name="student",
            table="student",
        ),
    ]
