# Generated by Django 4.2.7 on 2024-01-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_book_category_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="BookManagementProject/home/static/uploadedImages/default.jpg",
                upload_to="BookManagementProject/home/static/uploadedImages",
            ),
        ),
    ]
