# Generated by Django 4.2.7 on 2024-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Enter Password"
            ),
        ),
    ]
