# Generated by Django 4.2.7 on 2024-01-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_student_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=20, verbose_name="Enter Password"),
        ),
    ]
