# Generated by Django 4.2.7 on 2024-02-09 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0014_student_user_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="reserved_date",
            new_name="transaction_date",
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(default="Unknown Category", max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
