# Generated by Django 4.2.7 on 2024-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_rename_reserved_date_transaction_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(default="Unknown Category", max_length=30),
        ),
    ]
