# Generated by Django 4.2.7 on 2024-02-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(default="Unknown Category", max_length=10),
        ),
    ]
