# Generated by Django 4.2.7 on 2024-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_alter_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(default="Unknown Category", max_length=30),
        ),
    ]
